name: AnizottiRadiation
version: '${project.version}'
description: "Radiation event plugin for Anizotti"
main: org.cordell.com.anizottiradiation.AnizottiRadiation
api-version: '1.21'


commands:
  add_radiation_area:
    description: "Adds a new radioactive area."
    usage: "/add_radiation_area <x1> <y1> <z1> <x2> <y2> <z2>"
  clear_infection:
    description: "Remove any infection from player"
    usage: "/clear_infection <name>"
  find_cure_block:
    description: "Find cure block of radiation area"
    usage: "/find_cure_block"
  create_antidote:
    description: "Find antidote against radiation"
    usage: "/create_antidote"
